trigger:
  branches:
    include:
      - main

pool:
  vmImage: ubuntu-latest

variables:
  terraformVersion: '1.9.8'
  terraformWorkingDirectory: 'enviroment/dev'

stages:

# ==========================
# Terraform Plan
# ==========================
- stage: TerraformPlan
  displayName: 'Terraform Plan'

  jobs:
  - job: Plan
    displayName: 'Terraform Init, Validate & Plan'

    steps:

    # Install Terraform
    - task: TerraformInstaller@1
      displayName: 'Install Terraform'
      inputs:
        terraformVersion: '$(terraformVersion)'

    # Azure Login
    - task: AzureCLI@2
      displayName: 'Terraform Init & Plan'
      inputs:
        azureSubscription: 'YOUR-AZURE-SERVICE-CONNECTION'
        scriptType: 'bash'
        scriptLocation: 'inlineScript'
        addSpnToEnvironment: true
        inlineScript: |

          echo "Terraform version"
          terraform version

          echo "Moving to Terraform directory"
          cd $(terraformWorkingDirectory)

          echo "Terraform Init"
          terraform init

          echo "Terraform Validate"
          terraform validate

          echo "Terraform Plan"
          terraform plan -var-file="terraform.tfvars"
